### ISSUE TITLE
Compatibility with 5.1

### ISSUE THREAD

**Issue by Ora-solution** [stefandobre/Progress-Bar#1]
Thank for this plugin, Can you please guide that how can we used this plugin in 5.1.

Thanks.

**Comment by stefandobre** [comment]
Unfortunately APEX plugin export files are not backwards compatible. I also drew the line at 18.2 and am not planning to release anything under that.

If you really want to use it, what you can do is rebuild the plugin yourself in 5.1. Import the plugin into an app on apex.oracle.com to see how it's built. Then simply create a new plugin in your 5.1 instance, and copy the name, internal name, type, plsql code, attributes and all other settings like you see them in 19.1. The JavaScript files should technically work without any change (although I can't guarantee it)
